# Generated by Django 4.1.5 on 2024-03-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarrierApp', '0002_college_question_student_mark_course_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='is_college',
        ),
    ]
