# Generated by Django 4.1.5 on 2024-03-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarrierApp', '0003_remove_login_is_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
